name: CI/CD Pipeline

on:
  push:
    branches:
      - feature_1
  pull_request:
    branches:
      - feature_1

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
    # Проверяем репозиторий
    - name: Checkout code
      uses: actions/checkout@v3

    # Устанавливаем Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    # Устанавливаем зависимости проекта
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Проверка кода
    - name: Run tests
      run: |
      env:
        DB_ENGINE: ${{ secrets.DB_ENGINE }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
          python manage.py test

    # Деплой на сервер с использованием пароля
    - name: Deploy to Server
      env:
        HOST: ${{ secrets.SERVER_HOST }}          # IP-адрес
        USERNAME: ${{ secrets.SERVER_USER }}      # Пользователь для SSH
        PASSWORD: ${{ secrets.SERVER_PASSWORD }}  # Пароль для SSH
        PROJECT_DIR: ${{ secrets.SERVER_PROJECT_DIR }}  # Путь к проекту на сервере
      run: |
        sudo apt-get update && sudo apt-get install -y sshpass
        sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no $USERNAME@$HOST << EOF
          cd $PROJECT_DIR
          git pull origin feature_1
          source venv/bin/activate
          pip install -r requirements.txt
          python3 manage.py migrate
          python3 manage.py runserver
        EOF